name: "CI & CD"
on: [push]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v1
      - name: Login to Heroku
        run: heroku container:login

      - name: Build and Push
        run: heroku container:push -a amqa web

      - name: Deploy
        run: heroku container:release -a amqa web  
