# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v1
      - name: Login to Heroku
        run: heroku container:login

      - name: Build and Push
        run: heroku container:push -a amqa web

      - name: Deploy
        run: heroku container:release -a amqa web  
